name: github.event_name == 'release'

on:
  push:
   branches:
     - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller pyinstaller_recipe.spec
        shell: bash  # Needed for Windows compatibility
      
      - name: Rename Windows Binary
        if: matrix.os == 'windows-latest'
        run: mv dist/AI4Kids-AI-Rock-Paper-Scissors.exe dist/AI4Kids-Rock-Paper-Scissors-windows.exe  

      - name: Rename Linux Binary
        if: matrix.os == 'ubuntu-latest'
        run: mv dist/AI4Kids-AI-Rock-Paper-Scissors dist/AI4Kids-Rock-Paper-Scissors-linux.bin  
      
      - name: Rename macOS Binary
        if: matrix.os == 'macos-latest'
        run: mv dist/AI4Kids-AI-Rock-Paper-Scissors dist/AI4Kids-Rock-Paper-Scissors-macos.bin

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/AI4Kids-Rock-Paper-Scissors-windows.exe

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/AI4Kids-Rock-Paper-Scissors-linux.bin

      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: dist/AI4Kids-Rock-Paper-Scissors-macos.bin  # Upload renamed macOS binary

  release:
    needs: build  # Waits for the build job to finish
    #if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: dist/

      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: dist/

      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: macos-binary
          path: dist/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/AI4Kids-Rock-Paper-Scissors-windows.exe
            dist/AI4Kids-Rock-Paper-Scissors-linux.bin
            dist/AI4Kids-Rock-Paper-Scissors-macos.bin

      - name: Upload "Latest" Build
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            dist/AI4Kids-Rock-Paper-Scissors-windows.exe
            dist/AI4Kids-Rock-Paper-Scissors-linux.bin
            dist/AI4Kids-Rock-Paper-Scissors-macos.bin
